/**
 * /init — scan the current working directory and write a SINGULARITY.md
 * (rules + project summary) the agents will read on every dispatch.
 * Analog to OpenCode's `/init` writing AGENTS.md.
 */

import { promises as fs } from 'node:fs';
import { join } from 'node:path';

const SUMMARY_FILE = 'SINGULARITY.md';

async function tryRead(path: string): Promise<string | null> {
  try {
    return await fs.readFile(path, 'utf8');
  } catch {
    return null;
  }
}

async function listFiles(dir: string, depth = 2): Promise<string[]> {
  const out: string[] = [];
  async function walk(d: string, left: number): Promise<void> {
    if (left < 0) return;
    let entries;
    try {
      entries = await fs.readdir(d, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (e.name.startsWith('.') || e.name === 'node_modules' || e.name === 'dist') continue;
      const p = join(d, e.name);
      if (e.isDirectory()) await walk(p, left - 1);
      else out.push(p);
    }
  }
  await walk(dir, depth);
  return out;
}

export async function runInit(cwd = process.cwd()): Promise<{ ok: boolean; message: string }> {
  // Don't overwrite without confirmation
  const existing = await tryRead(join(cwd, SUMMARY_FILE));
  if (existing) {
    return {
      ok: false,
      message: `${SUMMARY_FILE} already exists. Delete it first or write to a different path.`,
    };
  }

  const pkg = await tryRead(join(cwd, 'package.json'));
  const tsconfig = await tryRead(join(cwd, 'tsconfig.json'));
  const readme = (await tryRead(join(cwd, 'README.md'))) ?? '';
  const files = await listFiles(cwd);

  let project = 'unknown project';
  if (pkg) {
    try {
      const p = JSON.parse(pkg);
      project = `${p.name ?? '(unnamed)'}${p.version ? '@' + p.version : ''} — ${p.description ?? ''}`;
    } catch {
      /* skip */
    }
  }

  const langs = new Set<string>();
  for (const f of files) {
    if (f.endsWith('.ts') || f.endsWith('.tsx')) langs.add('TypeScript');
    else if (f.endsWith('.js') || f.endsWith('.jsx')) langs.add('JavaScript');
    else if (f.endsWith('.py')) langs.add('Python');
    else if (f.endsWith('.go')) langs.add('Go');
    else if (f.endsWith('.rs')) langs.add('Rust');
    else if (f.endsWith('.rb')) langs.add('Ruby');
    else if (f.endsWith('.java')) langs.add('Java');
  }

  const top = readme.split('\n').slice(0, 5).join('\n');

  const md = [
    '# Project rules for Singularity',
    '',
    '<!-- Auto-generated by /init. Edit freely. Read by every dispatch. -->',
    '',
    '## What this project is',
    project,
    '',
    'Languages detected: ' + (langs.size ? [...langs].join(', ') : 'unknown'),
    'Has TypeScript config: ' + (tsconfig ? 'yes' : 'no'),
    '',
    '## README excerpt',
    '',
    top || '(no README found)',
    '',
    '## Rules for agents',
    '',
    '- Stay on-topic for this project.',
    '- Mark cross-pane facts with `NOTE:`.',
    '- Open every response with `CONFIDENCE: 0.0-1.0`.',
    '- Ask via `CLARIFY:` instead of guessing.',
    '- Prefer small, reversible changes.',
    '',
  ].join('\n');

  // Journaled write — /rollback can undo /init too.
  const { shadowWrite } = await import('./shadowfs.js');
  const entry = await shadowWrite(join(cwd, SUMMARY_FILE), md, { label: '/init' });
  return {
    ok: true,
    message: `wrote ${SUMMARY_FILE} (${langs.size} langs, ${files.length} files; journaled ${entry.id.slice(0, 12)})`,
  };
}

/** Load and return SINGULARITY.md (or AGENTS.md / CLAUDE.md as fallback). */
export async function loadProjectRules(cwd = process.cwd()): Promise<string | null> {
  const candidates = ['SINGULARITY.md', 'AGENTS.md', 'CLAUDE.md'];
  for (const c of candidates) {
    const txt = await tryRead(join(cwd, c));
    if (txt) return `[project rules from ${c}]\n${txt.slice(0, 4000)}\n[/project rules]`;
  }
  return null;
}
